version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:1-sdk
    steps:
      - checkout
      - run: cd ID4iClientSample && dotnet restore
      - run: cd ID4iClientSample && dotnet build
